"""Generate docs/schema.md from BigQuery INFORMATION_SCHEMA — never invent schema.

Usage:
    uv run python scripts/generate_schema_doc.py

Queries `bigquery-public-data.thelook_ecommerce.INFORMATION_SCHEMA.COLUMNS`
once for the four tables the agent uses and rewrites `docs/schema.md`.
Re-run whenever the upstream dataset changes.
"""

from __future__ import annotations

import sys
from pathlib import Path

from dotenv import load_dotenv

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from tools.bigquery_client import DATASET, BigQueryClient  # noqa: E402

TABLES = ("orders", "order_items", "products", "users")

QUERY = f"""
SELECT table_name, column_name, data_type, is_nullable
FROM `{DATASET}.INFORMATION_SCHEMA.COLUMNS`
WHERE table_name IN {TABLES!r}
ORDER BY table_name, ordinal_position
LIMIT 500
"""

HEADER = f"""# BigQuery schema — `{DATASET}`

> Generated by `scripts/generate_schema_doc.py` from `INFORMATION_SCHEMA.COLUMNS`.
> Do not edit by hand — re-run the script to refresh.

Tables used by the agent: {", ".join(f"`{t}`" for t in TABLES)}.
"""


def main() -> None:
    load_dotenv(REPO_ROOT / ".env")
    client = BigQueryClient()
    df = client.execute(QUERY)
    if df.empty:
        raise SystemExit("INFORMATION_SCHEMA returned no rows — aborting, schema.md untouched.")

    sections: list[str] = [HEADER]
    for table in TABLES:
        table_df = df[df["table_name"] == table]
        sections.append(f"\n## `{table}`\n")
        sections.append("| Column | Type | Nullable |")
        sections.append("|---|---|---|")
        for row in table_df.itertuples(index=False):
            sections.append(f"| `{row.column_name}` | {row.data_type} | {row.is_nullable} |")

    out_path = REPO_ROOT / "docs" / "schema.md"
    out_path.write_text("\n".join(sections) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(df)} columns across {len(TABLES)} tables).")


if __name__ == "__main__":
    main()
